version: '3'

services:

  mysql:
    image: mysql:8
    volumes:
      - './tmp/data:/var/lib/mysql'
    command: ["mysqld", "--innodb_force_recovery=0", "--innodb_fast_shutdown=1"] 
    ports:
      - '3306:3306'
    env_file:
      - .env

 
  app:
    build: .
    image: ghcr.io/democraciaenred/e-voto:latest
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    links:
      - mysql
    env_file:
      - .env
